### PR TITLE
Fix Subscriptions

### PR DESCRIPTION
**Pull request by anthonysikaneta**
**Changes**

* Point subscription form/button to Tally

**Testing**

* Click the subscribe button in the footer and enter your email on the next page.
* If you need to see how it looks in the backend, reach out for a screenshot or creds.

### CODE REVIEW

**Comment by Zikhalo** [comment]
1. The subscribe button in the footer does lead to the next page (to Tally) where an email is required well and good.
2. If a screenshot can be provided for the backend.
3. Will subscribing give any notifications for the community section? If so then we may have to look at the wording, "Get notified when a new opportunity is added."

**Comment by anthonysikaneta** [comment]
> 2. If a screenshot can be provided for the backend.

Sent you the creds. Didn't see your submission.

> 3. Will subscribing give any notifications for the community section? If so then we may have to look at the wording, "Get notified when a new opportunity is added."

Well we'll have their emails which will be used for any and all notifications. If they opt in to have those notifications then we should set them up accordingly. LinkedIn for example curates opportunities in an email and sends them to me at certain intervals.

**Comment by Zikhalo** [comment]
I've seen the credentials and the backend. I also entered my email to see what it would lead to. Seems good. 

As for notifications, if it's any and all notifications then would the wording, "Get notified when a new **post** is added." work? That's all i have before closing this.

**Comment by anthonysikaneta** [comment]
> would the wording, "Get notified when a new post is added." work?

How about "new content"?

**Comment by Zikhalo** [comment]
I'm indifferent so let us go with "new content" for the time being. I'll make note of it, and I'll bring up the two options we've mentioned in our group chat to get feedback there.

**Review by MichaelChuba — APPROVED** [review]

**Pull request merged**
