### PR TITLE
Limit Logged Out Functionality

### PR DESCRIPTION
**Pull request by anthonysikaneta**
**Changes**

- Hide functionality if not logged in
- Limit opportunities to 6 if not logged in
- Update "Nothing" component copy and presentation
- Remove unused filter logic

**Testing**

1. Go to the opportunity and community pages
2. Observe that there is a call to action prompting for sign up if the user wants to see more

### CODE REVIEW

**Comment by Zikhalo** [comment]
1. The community page doesn't have a "Get Started" button
2. Job opportunities also doesn't have a "Get Started" button, but this could be due to no postings listed

**Comment by anthonysikaneta** [comment]
@Zikhalo correct - jobs has not postings

I fixed the issue with the buttons/colors, you can check now.

**Comment by Zikhalo** [comment]
I've had a look and saw the changes. The only feedback I have before closing this is to have a slight space between the opportunities and the blue colored box. It could have similar spacing to the list of opportunity boxes. 3 boxes (horizontally), space between, 3 boxes, space between.

**Comment by anthonysikaneta** [comment]
> have a slight space between the opportunities and the blue colored box.

done.

@Zikhalo

**Review by MichaelChuba — APPROVED** [review]

**Pull request merged**
