### PR TITLE
chore: simplify technical language

### PR DESCRIPTION
**Pull request by tonydollarsign**
**Changes**

Screenshot 2023-12-21 at 12 01 53

### CODE REVIEW

**Comment by noelsich** [comment]
One last one, the Password, which I didn't notice in the original #149 ticket

string

**Comment by noelsich** [comment]
> @noelsich done.

Checked it out, its Perfect

**Review by noelsich — APPROVED** [review]
great

**Review by Mwimwii — APPROVED** [review]
My eyes are closed, I know the code is heat 🔥

**Pull request merged**
